### ISSUE TITLE
can't login, or navigate after login

### ISSUE THREAD

**Issue by arnobase** [colorfulnotion/polkaholic#25]
If I try to login (https://polkaholic.io/login)
there is no error message and I'm not logged in
if I try to create my user again, message says "User already exists."

when I connect through http (I'm not redirected anyway), I see the "logout" link in place of "login" link
but if I navigate anywhere, I'm logged out

**Comment by sourabhniyogi** [comment]
@arnobase Thank you for the report -- we believe we have fixed the issue -- can you kindly check that it is no longer an issue for you?

Fixed in #30: https://github.com/colorfulnotion/polkaholic/commit/23b53fcc3007b6af3503b92fadc91e514c205d57#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346L79 

Background: 
* When our load balancer auto scaled, sessions were't sticky between instances in the load balancer -- we had to drop a `secure` bit for the port forwarding involved

**Comment by mkchungs** [comment]
Seems fixed. Closing the issue for now. But feel free to re-open it
