### ISSUE TITLE
Wrong fee on transfer bridge

### ISSUE THREAD

**Issue by jacksonbaleeiro** [colorfulnotion/polkaholic#271]
When the fee cust just 10 LIT, i’ve use transfer bridge and fee cust 28 LIT, it is not right, and i lost all my unlocked LIT, please help me.

**Comment by mkchungs** [comment]
Hello there, we will need a bit more context to inspect issue like this: can you please share your ss58 address / extrinsicHash with us so we could better assit you?

**Comment by mkchungs** [comment]
Thanks for reporting the issue, the correct txn fee for this extrinsic should be 0.000231300744 LIT (instead of 23.1300744 LIT)

For your test case: https://polkaholic.io/tx/0x0b755a79b256976f44dfa4c987241bf09e81353088139575ce2d1f422a9a84fd

The txnfee computation logic is fixed in #268 2 weeks ago but we didn't get the chance to reindex old Litentry block yet. We will do it this week and roll out the fix to polkaholic api.
